### ISSUE TITLE
 @pub-type depreciated in JATS

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/package-ejp-raw-output-zip#35]
## Problem / Motivation

- WHO: Production
- WHEN/WHERE/WHAT: remove @pub-type="epub" from this line of XML:
```<issn publication-format="electronic" pub-type="epub">2050-084X</issn>```
- WHY: this tag is depreciated in JATS

## Proposed solution
-https://jats.nlm.nih.gov/archiving/tag-library/1.2d1/attribute/publication-format.html
- ```<issn publication-format="electronic" pub-type="epub">2050-084X</issn>```should be replaced with```<issn publication-format="electronic">2050-084X</issn>```

## Clarification needed and assumptions
None

---

## Tasks
- [ ] remove @pub-type="epub" from this line of XML:
```<issn publication-format="electronic" pub-type="epub">2050-084X</issn>```
- [ ] check it still works on PMC
- [ ] this is not used for any logic in the bot

## Technical notes
@gnott
